import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
// Import the FontAwesomeIcon component
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
// import the icons you need
import {
  faFacebook,
  faYoutube,
  faTwitter,
  faInstagram,
} from '@fortawesome/free-brands-svg-icons';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Footer Responsif dengan Nextjs & Bootstrap 5</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Footer Responsif dengan Nextjs & Bootstrap 5
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className="bg-dark text-white pt-5">
        <div className="container">
          <div className="row">
            <div className="col-md-3">
              <h3>Title</h3>
              <hr />
              <ul className="list-unstyled text-secondary">
                <li>Subtitle</li>
                <li>Subtitle</li>
                <li>Subtitle</li>
                <li>Subtitle</li>
              </ul>
            </div>
            <div className="col-md-3">
              <h3>Title</h3>
              <hr />
              <ul className="list-unstyled text-secondary">
                <li>Subtitle</li>
                <li>Subtitle</li>
                <li>Subtitle</li>
                <li>Subtitle</li>
              </ul>
            </div>
            <div className="col-md-3">
              <h3>Title</h3>
              <hr />
              <ul className="list-unstyled text-secondary">
                <li>Subtitle</li>
                <li>Subtitle</li>
                <li>Subtitle</li>
                <li>Subtitle</li>
              </ul>
            </div>
            <div className="col-md-3">
              <h2 className="text-md-end">
                JAGO <span className="text-primary">KODE</span>
              </h2>
              <ul className="list-unstyled text-secondary text-md-end mt-4">
                <li>Address</li>
                <li>Telephone</li>
                <li>Email</li>
              </ul>
            </div>
            <div className="col-md-3"></div>
          </div>
          <hr />
          <div className="row">
            <div className="col-md-4">
              <h2>Hubungi Kami</h2>
              <h1 className="text-primary">000011112222</h1>
            </div>
            <div className="col-md-4 d-flex flex-column justify-content-center align-items-start">
              <p className="bg-primary py-2 px-3">Ikuti Kami</p>
              <div className="d-flex pb-2">
                <FontAwesomeIcon
                  icon={faFacebook}
                  style={{ width: '25px', height: '25px' }}
                />
                <FontAwesomeIcon
                  icon={faInstagram}
                  style={{ width: '25px', height: '25px' }}
                />
                <FontAwesomeIcon
                  icon={faTwitter}
                  style={{ width: '25px', height: '25px' }}
                />
                <FontAwesomeIcon
                  icon={faYoutube}
                  style={{ width: '25px', height: '25px' }}
                />
              </div>
            </div>
            <div className="col-md-4">
              <Image
                src="/images/payments_options.png"
                alt="payments_options"
                width={200}
                height={100}
                className="img-fluid bg-white"
              />
            </div>
          </div>
        </div>
        <div className="copyright bg-primary py-3">
          <div className="container">
            <div className="row">
              <div className="col-md-6">
                <small>HAKCIPTA &copy; 2022. JAGOKODE. </small>
              </div>
              <div className="col-md-6">
                <small className="text-md-end">
                  PERJANJIAN LISENSI PENGGUNA | KEBIJAKAN PRIVASI | S&K
                </small>
              </div>
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
}
